# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_auto_20161116_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courseapp.Course'),
        ),
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
