# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_auto_20161116_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
